nats-io/nack

README.md

There was a really minor typo of backtick lying around.
Also, I made it clearer with shell prompt to indicate which shell session you are on (`nats-box` or outside cluster).
As a complete side note, I have been putting my own note of each setup step - it's just an idea but there may be some documentation setup this repo can benefit from as well, such as using KinD.
https://github.com/rytswd/simple-nats-js/tree/master/docs/nack-based
(This is truly just for my own testing and understanding)

Correct typo and add kubectl for verification

---

README.md

Forgot to update the format with #7 😓

Correct code block format

---

Makefile

I was looking for the new image today, maybe this was a problem when publishing?

Make makefile use actual git tag

---

.gitignore
Makefile
README.md
cmd/jetstream-controller/main.go
cmd/nats-server-config-reloader/main.go
docker/nats-server-config-reloader/Dockerfile
go.mod
go.sum
pkg/natsreloader/natsreloader.go
pkg/natsreloader/natsreloadertest/natsreloader_test.go
vendor/github.com/fsnotify/fsnotify/.editorconfig
vendor/github.com/fsnotify/fsnotify/.gitattributes
vendor/github.com/fsnotify/fsnotify/.gitignore
vendor/github.com/fsnotify/fsnotify/.travis.yml
vendor/github.com/fsnotify/fsnotify/AUTHORS
vendor/github.com/fsnotify/fsnotify/CHANGELOG.md
vendor/github.com/fsnotify/fsnotify/CONTRIBUTING.md
vendor/github.com/fsnotify/fsnotify/LICENSE
vendor/github.com/fsnotify/fsnotify/README.md
vendor/github.com/fsnotify/fsnotify/fen.go
vendor/github.com/fsnotify/fsnotify/fsnotify.go
vendor/github.com/fsnotify/fsnotify/go.mod
vendor/github.com/fsnotify/fsnotify/go.sum
vendor/github.com/fsnotify/fsnotify/inotify.go
vendor/github.com/fsnotify/fsnotify/inotify_poller.go
vendor/github.com/fsnotify/fsnotify/kqueue.go
vendor/github.com/fsnotify/fsnotify/open_mode_bsd.go
vendor/github.com/fsnotify/fsnotify/open_mode_darwin.go
vendor/github.com/fsnotify/fsnotify/windows.go
vendor/modules.txt

This adds the nats-server-config-reloader project to nack.

Add nats-server-config-reloader

---

controllers/jetstream/consumer.go
deploy/crds.yml
pkg/jetstream/apis/jetstream/v1beta1/consumertypes.go

Add maxAckPending option to consumer

---

cmd/jetstream-controller/main.go
controllers/jetstream/controller.go

Add NATS TLS (tlsca, tlscert, tlskey) options

---

README.md

This adds a section on getting started with Accounts. It shows a full
example of how to configure a custom NATS Server URL and TLS certs to
create Streams and Consumers.

Add readme section about Accounts

---

cmd/nats-server-config-reloader/main.go
pkg/natsreloader/natsreloader.go
pkg/natsreloader/natsreloadertest/natsreloader_test.go

Port of PR from nats-operator: https://github.com/nats-io/nats-operator/pull/338
Signed-off-by: Waldemar Quevedo <waldemar.quevedo@gmail.com>

Add support to send custom signal via reloader

---

docker/nats-server-config-reloader/Dockerfile

Signed-off-by: Waldemar Quevedo <wally@synadia.com>

Updates to reloader dockerfile

---

cicd/Dockerfile
cicd/assets/entrypoint.sh
docker-bake.hcl

- Switching to entrypoint script
- Changing root symlink to retain binary name

Updating dockerfile entrypoint

---

docker/nats-boot-config/Dockerfile
docker/nats-server-config-reloader/Dockerfile

This change addresses a couple of critical vulnerabilities

Update base docker image to alpine 3.17 to address vulnerabilities

---

controllers/jetstream/consumer.go

This PR adds the functionality in the consumer controller to use the userCredentials specified in the Account resource.

Implement linked account userCredentials for consumer management

---

README.md

Adding Badges to readme

---

README.md
deploy/examples/stream.yml
deploy/examples/stream_mirror.yml
deploy/examples/stream_placement.yml
deploy/examples/stream_sources.yml
deploy/examples/streamtemplate.yml

closes #157
Signed-off-by: Tomasz Pietrek <tomasz@nats.io>

Fix installation guide

---

controllers/jetstream/stream.go

Signed-off-by: Piotr Piotrowski <piotr@synadia.com>

Fix setting placement on stream update

---

.github/workflows/deps-release-tag.yaml

target release needs `on: workflow-dispatch`

move release workflow to deps patch release

---

cmd/jetstream-controller/main.go
internal/controller/consumer_controller_test.go
internal/controller/keyvalue_controller_test.go
internal/controller/objectstore_controller_test.go
internal/controller/stream_controller_test.go
internal/controller/suite_test.go

Resolves issue with Controller Runtime backend when using a namespaced Service Account Role not scoping watched resources
Resolves #243

Resolve Namespace Issue with Controller Runtime Backend

---

internal/controller/client.go
internal/controller/connection_pool.go
internal/controller/consumer_controller_test.go

Client should not use strict mode in most use casees.
That caused the issue in #245 
closes #245 
Signed-off-by: Tomasz Pietrek <tomasz@nats.io>

Remove pedantic mode from client connection

---

controllers/jetstream/consumer.go
controllers/jetstream/consumer_test.go

closes #270 
Signed-off-by: Tomasz Pietrek <tomasz@nats.io>

Add missing deliverLastPerSubject policy

---

internal/controller/consumer_controller.go
internal/controller/consumer_controller_test.go

closes #280 
Signed-off-by: Tomasz Pietrek <tomasz@synadia.com>

Fix `lastPerSubject` causing error
